### ISSUE TITLE
prefer cabal when there is a cabal.project.{local, freeze}

### ISSUE THREAD

**Issue by fommil** [mpickering/hie-bios#10]
I propose that `cabal-install` be the preferred backend if there is a `cabal.project.local` or `cabal.project.freeze` file, even if there is a `stack.yaml`, as this implies that the user has taken steps to prefer `cabal`.

Generally it would be good to allow the user to provide an envvar to choose the preference when there is ambiguity. e.g. many simple projects have a `stack.yaml` because somebody requested it. An envvar might just be the simplest option all around instead of getting into complex rules.

**Comment by mpickering** [comment]
A configuration file should be specified if the automatic configuration fails. The cabal configuration is ranked below the other configuration options as cabal has the worst support for working out which component you need to start the repl (ie, there's no way to map a filepath to a component). If you use cabal it is likely you have to specify a config file anyway to specify the right component.

**Comment by fommil** [comment]
I assume you've seen http://hackage.haskell.org/package/cabal-helper ?

**Comment by mpickering** [comment]
Yes, `cabal-helper` needs to be integrated into `hie-bios` but `hie-bios` was created to avoid depending on only `cabal-helper`.

**Comment by fommil** [comment]
btw my usecase is for the batch compiler not the repl. I would like to be able to launch tools that have access to ghc-lib (i.e. to see `.hi` files, source code bases, and in the future `.hie` files).

**Comment by mpickering** [comment]
Yes. The guiding principal behind `hie-bios` is to not link against any specific library. This shifts the responsibility for describing the right environment to the build tool rather than the tooling author. 

Anyone can write their own tool using whatever libraries they like and provide a suitable command line interface to query.
