### ISSUE TITLE
Tests fail when run inside nix builder

### ISSUE THREAD

**Issue by mpickering** [mpickering/hie-bios#107]
How do the cradle test interplay with nix? I'm currently trying to integrate `hie-bios-0.3` into `nixpkgs` and I get a lot of errors like:

```
    multi-cabal:               FAIL (0.07s)
      Finding Cradle
      Loading Cradle
      Initialise Flags (0.07s)
        cabal: streamingProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

_Originally posted by @turion in https://github.com/mpickering/hie-bios/issues/25#issuecomment-567011935_

**Comment by mpickering** [comment]
@turion You need to run the tests in an environment which has `stack` `cabal` and `ghc` available on the path. I would guess the pure nix builder environment does not satisfy this.

**Comment by turion** [comment]
Thanks for opening this ticket. Check out the recent `haskell-updates` branch of `nixpkgs` (https://github.com/NixOS/nixpkgs/tree/haskell-updates), and try `nix-build -A haskellPackages.hie-bios`. It fails with the above errors.

**Comment by mpickering** [comment]
I suspect the right solution here is to use `dontCheck`.

**Comment by turion** [comment]
In that case it seems like we need to fix it on the `nixpkgs` side. Tracking progress in https://github.com/NixOS/nixpkgs/pull/75869

**Comment by turion** [comment]
> I suspect the right solution here is to use `dontCheck`.

Yes, that's an option. Would be nice to run the tests though, because it gives some feeling for how to set up `hie` on `nix`, and it's a free CI for you ;)

**Comment by mpickering** [comment]
Closing as out of scope -- this is purely a nix issue.
