### ISSUE TITLE
invalid argument (Exec format error)

### ISSUE THREAD

**Issue by LukaHorvat** [mpickering/hie-bios#11]
I don't know if this is the right repository to raise the issue since I'm getting it by invoking "hie-core" in my project(s).

Anyways, when running hie-core in any of my stack projects I get something like this:

```
[1/6] Finding hie-bios cradle
Cradle {cradleRootDir = "C:\\Users\\darwi\\Projects\\basic", cradleOptsProg = CradleAction: stack}

[2/6] Converting Cradle to GHC session
#!/usr/bin/env bash
if [ "$1" == "--interactive" ]; then
  pwd
  echo "$@"
else
  ghc "$@"
fi

res
  (ExitFailure 1,"C:\\msys64\\tmp\\wra530A: startProcess: invalid argument (Exec format error)\n",["-package-db","C:\\Users\\darwi\\Projects\\basic\\.stack-work\\install\\5fdbb79e\\pkgdb","-package-db","C:\\sr\\snapshots\\c6f920a2\\pkgdb","-package-db","C:\\Users\\darwi\\AppData\\Local\\Programs\\stack\\x86_64-windows\\ghc-8.6.4\\lib\\package.conf.d"],"")
hie-core.exe: CradleError "C:\\msys64\\tmp\\wra530A: startProcess: invalid argument (Exec format error)\n"
```

I'm on Windows 10 64bit. Let me know what additional info you want me to provide.
Also, sorry if this is unrelated to hie-bios. hie-core doesn't seem to have a dedicated issue board.

**Comment by mpickering** [comment]
Probably no one has ported over the `stack` cradle wrapper to work on windows yet. The library isn't finished yet so I'm afraid it's use at your own risk and fix problems yourself at this stage.

**Comment by jneira** [comment]
@LukaHorvat hi! it throwed another error for me but i get to make it work with #50

**Comment by fendor** [comment]
I suspect this is solved since multiple users are using hie-bios via hie and ghcide on windows. Feel free to reopen if the problem persists.
