### ISSUE TITLE
hie-bios needs a hie.yaml

### ISSUE THREAD

**Issue by ndmitchell** [mpickering/hie-bios#111]
Before it would have worked by default. Now I get:

```
CradleError (ExitFailure 1) ["Failed to parse result of calling cabal","","cabal: No targets given and there is no package in the current directory. Use\nthe target 'all' for all packages in the project or specify packages or\ncomponents by name or location. See 'cabal build --help' for more details on\ntarget options.\n\n",""]
```

It seems unfortunate that nothing works out of the box anymore.

**Comment by mpickering** [comment]
It worked by default before because there was only one component I think? The cabal cradle has not changed much since the last release.

**Comment by ndmitchell** [comment]
Maybe it hasn't worked for ages - I don't remember how long ago it was I last tested it. Either way, perhaps hie-bios should have a hie.yaml, given it's encouraging every other Haskell repo to add one :)

**Comment by mpickering** [comment]
I added one now.
