### ISSUE TITLE
Add functional test suite

### ISSUE THREAD

**Issue by jneira** [mpickering/hie-bios#113]
* To tackle issues like #110 and test all the code path (the main exec entry point, compiling the wrapper and run it, etc)

**Comment by fendor** [comment]
BIOS Tests are functional tests right? We need a Windows ci

**Comment by mpickering** [comment]
If we could force one code path to use the wrapper, even on linux then that would be an improvement.

**Comment by jneira** [comment]
@fendor is right: the actual tests already cover the compilation and execution of the wrapper so only with Windows CI we had tackle the recent issues with it

However, i think a functional test suite would be still valuable, although not so important: we could check all `hie-bios` subcommands, like `hie-bios debug` (in general, the Main module) and all the code paths originated in it and no covered with existing tests

**Comment by jneira** [comment]
I think this is not critical so closing
