### ISSUE TITLE
Improve interface of `loadCradle`

### ISSUE THREAD

**Issue by fendor** [mpickering/hie-bios#139]
The current interface `loadCradle :: FilePath -> Cradle Void` has multiple problems.
After loading a cradle without a custom parser, extending it to something like `Cradle CabalHelper` requires to manually pattern match on the `ActionName` which is not nice. 
Moreover, it requires a `FromJSON Void` instance that is fairly new and only very recently added to the `yaml` library (Version 0.11.2.0). This could make updating for some applications harder.

Some ideas to mitigate these issues,
* Use `Cradle ()` to avoid that `yaml` is required in its most recent version.
  * Could improve readability (but intention might be clouded)
  * Does not allow us to model that a certain ActionName Constructor is just not 
* Drop the type parameter and just turn `ActionName.Other` constructor into taking a String.
  * Not really type checkable
  * No type params
* Provide a function: `Cradle Void -> Cradle a`
  * Not sure how that should actually work without being partial (Or at least the compiler thinks we are partial).
* Provide a function `a -> Cradle Void -> Cradle a`
  * add default value that should actually never be used.

Maybe there are other solutions as well? Please suggestions or preferences.

**Comment by ndmitchell** [comment]
I don't see requiring a modern yaml library as problematic, provided it still compiles on older GHC's. That said, Void is confusing, I'd just use `()` as that's usually just fine.

**Comment by fendor** [comment]
Would a `Functor` instance make sense for `Cradle`? It satisfies all laws, afaict.

**Comment by ndmitchell** [comment]
A Functor instance is often useful, and fairly cheap with DeriveFunctor, so I always go for it if I can.
