### ISSUE TITLE
Configuration for multiple cabal packages

### ISSUE THREAD

**Issue by robrix** [mpickering/hie-bios#14]
We build https://github.com/github/semantic with `cabal`, and have two different cabal packages defined in the repo (`semantic` and `semantic-core`), with disjoint sets of source files for each.

Is there any way to tell `hie-bios` that I want to use `cabal: {component: "lib:semantic"}` in `src`, and `cabal: {component: "lib:semantic-core"}` in `semantic-core/src`? I’ve tried adding separate `hie.yaml` files in the root of the repo & the `semantic-core` dir, but it doesn’t seem to notice the latter, and so I only get results (using `hie-core`) shown for modules belonging to `semantic`. (On the other hand, if I add a `hie.yaml` containing `cradle: {cabal: {component: "lib:semantic-core"}}` to the root of the project, then I only get results shown for modules belonging to `semantic-core`.)

I assume that I could do this via a `.hie-bios` program & the appropriate `bios` cradle, but I’m not clear on how to generate the list of arguments it should return—I really do want `cabal` to generate them for me.

**Comment by mpickering** [comment]
Which branch of `haskell-ide-engine` are you using? You need to use my branch for anything to work so best to establish that first. I would think adding `hie.yaml` files in the right sub directories should work but I will try it myself.

**Comment by robrix** [comment]
Ah, I’m not presently using `haskell-ide-engine`, but rather [`hie-core`](https://github.com/digital-asset/daml/tree/master/compiler/hie-core#readme).

**Comment by mpickering** [comment]
I don't think hie-core supports multiple components currently.

**Comment by cocreature** [comment]
@mpickering is right. At the moment, one instance of `hie-core` works with one GHC session. So you either have to spawn multiple instances of `hie-core`, one per component (the details of how you do that probably depend on your editor) or you need to write a `.hie-bios` file that does something like calling `cabal v2-repl` on each component and then merges the flags.

**Comment by robrix** [comment]
Ahhh, I see! Thanks very kindly for the explanation 👍

**Comment by mpickering** [comment]
I tried `semantic` on my fork of HIE and it ran into two problems.

1. The RTS options in the cabal file are not ignored properly by HIE. It would be good to pass some
similar options to HIE by default anyway.
2. The multi-component loading doesn't work properly as the project root is assumed to be where the `hie.yaml` file is. In this case `semantic-core` still loads but the options in the `cabal.project` file are ignored.
