### ISSUE TITLE
Allow specifying the GHC to be used for the cabal cradle

### ISSUE THREAD

**Issue by alanz** [mpickering/hie-bios#148]
A standard idiom is `cabal new-configure --with-compiler=ghc-8.8.2`.

Given a `hie.yaml` file is intended to set up the local developer's intentions, we should be able to specify the GHC compiler version with a cabal cradle.

As a side-effect, this can help tooling like `hie` and its successors to choose an appropriate version to run.

**Comment by sureyeaah** [comment]
I would like to take this on. It seems like a relatively easy task. What do you think?

**Comment by fendor** [comment]
That sounds nice! However, designing a nice API doesnt sound as easy. Also, we got to think about https://github.com/mpickering/hie-bios/issues/44 of which this could be an extension. In a different approach, we could use cabal-install-parsers in hie/ghcide/hls to find the ghc version automatically. 
I am happy for PR's but would like to discuss design ideas such as modifications in `hie.yaml` as well as changes in the types before.

**Comment by sureyeaah** [comment]
Has there been any progress on #44 ?

**Comment by fendor** [comment]
I have been implementing a prototype but there is not much to show at the moment. 
First step would be discussing an `hie.yaml` format for it and should it be a global option, per cradle, etc... A lot to discuss. If you have any ideas, you can write them in #44!

**Comment by fendor** [comment]
@alanz Would it be better if `hie-bios` honours the configuration in `cabal.project`, etc... or if it was possible to specify the ghc version in `hie.yaml`?

**Comment by jneira** [comment]
both? 😝

**Comment by fendor** [comment]
Not sure if both is really nice. E.g. `cabal configure -w ghc-8.6.4` but you specify a different ghc in `hie.yaml`?

**Comment by alanz** [comment]
Hmm, I have been mentally using a workflow where the `cabal.project` is under version control, and is "general", without specifying the GHC version.  This simplifies things like CI.

Then when working with a particular GHC version you configure it to use that. And I guess the same effect comes from using `cabal.project.local`.

But I have had experiences where I am working on a project which I manually configured with one version of GHC (say ghc-8.8.2), and then hie-bios periodically reconfigures it with the "default" ghc, being 8.6.5. So you end up fighting with it.

**Comment by fendor** [comment]
Yes, and I think the most intuitive approach would be that hie-bios uses the correctly configured version from `cabal.project.local`. However, if it does that, a custom field in `hie.yaml` would be superfluous.

**Comment by jneira** [comment]
closing as duplicate in favor of #194 (As there is a technical discussion on how to accomplish and a linked pr)
