### ISSUE TITLE
index-state from cabal.project

### ISSUE THREAD

**Issue by alanz** [mpickering/hie-bios#150]
Does `hie-bios` make use of the `index-state` field from the `cabal.project` file, or can a similar effect be achieved?

At the moment (index state 2020-02-01T08:48:32Z), https://github.com/haskell/ide does not build, but it does with an earlier one (2020-01-31T22:59:59Z) (Aside, makes you wonder what else Brexit will break).

How can a cabal cradle be told to use the earlier one?

**Comment by fendor** [comment]
Cabal cradle uses `cabal v2-repl` to find the compiler flags, I would assume that the `index-state` is read by that as well, so should be honoured.
