### ISSUE TITLE
Expose smart constructor(s) from Hie.Bios.Cradle to create cradles programatically

### ISSUE THREAD

**Issue by jneira** [mpickering/hie-bios#165]
It seems the unique way to create cradles is through yaml configuration.
I think sometimes could be useful being able to create cradles programatically, without an intermmediate yaml config.
Maybe exposing [`getCradle`](https://github.com/mpickering/hie-bios/blob/master/src/HIE/Bios/Cradle.hs#L87) would be enough.

My actual use case is to create a simple direct cradle to load the `Path_package_name.hs` magic modules generated by cabal in hls.

**Comment by fendor** [comment]
In haskell-ide-engine, we first check if there is a yaml configuration in the directory. If there isnt, we try to use cabal-helper to produce a `Cradle` programmatically. 
I dont understand how `getCradle` could be more useful?

Also, constructors of `Cradle` are all exposed in https://github.com/mpickering/hie-bios/blob/15d855cdefee490ce549c51458580ee4195c559d/src/HIE/Bios/Types.hs#L34

**Comment by jneira** [comment]
> Also, constructors of Cradle are all exposed in 
yeah, i am able to copy [`directCradle`](https://github.com/mpickering/hie-bios/blob/master/src/HIE/Bios/Cradle.hs#L295) thanks to that, but i would prefer to no have to do it
My idea was make public the "smart" constructors from `Hie.Bios.Cradle` (but `getCradle` is the main one so it is enough)
Direct cradle is relatively simple but i guess applications would want to create more complex ones and the amount of code copied would be annoying.

> I dont understand how getCradle could be more useful?

I wanted to create a cradle programatically to manage `Paths_` modules and the cabal cradle cant handle them (maybe it is possible and i've not seen the way to do it) so i want to use a direct cradle (cause `Paths_`modules can be compiled without any compiler args)

**Comment by jneira** [comment]
After a irc talk we have agreed that the load of the `Paths_` module should be done in the cabal-helper cradle itself.
However i still think to expose a function to create cradles programatically could be useful to client code.
It seems to me `getCradle` could be the right one cause it does not expose too much details (hie-bios could add new cradles and the function will continue working). The params are all haskell types that you can create but they are simpler than cradles.
