### ISSUE TITLE
Failed to parse result of calling cabal: doesn't output flags for a specific module

### ISSUE THREAD

**Issue by chshersh** [mpickering/hie-bios#170]
Hi, thanks for working on this fantastic tool! `hie-bios` is super useful for discovering GHC flags used to build Haskell modules.

Unfortunately, I'm having some troubles while using the tool on a cabal project. I'm trying to run `hie-bios` on the [`validation-selective`](https://github.com/kowainik/validation-selective) Haskell library.

First, I've created the following `hie.yaml` file:

```yaml
cradle:
  cabal:
    - path: "./src"
      component: "lib:validation-selective"
```

Then, I'm running the following command:

```
HIE_BIOS_OUTPUT=out hie-bios flags src/Validation.hs
```

However, I see that it fails with the following error:

```
Failed to show flags for "src/Validation.hs": ["Failed to parse result of calling cabal","Resolving dependencies...\nBuild profile: -w ghc-8.8.3 -O1\nIn order, the following will be built (use -v for more details):\n - validation-selective-0.0.0.1 (lib) (configuration changed)\nConfiguring library for validation-selective-0.0.0.1..\nPreprocessing library for validation-selective-0.0.0.1..\n","",""]
```

I can see that the content of the `out` file is not empty, specifically, the file is the following:

```
/home/shersh/haskell/kowainik/validation-selective
--interactive
-fbuilding-cabal-package
-O0
-outputdir
/home/shersh/haskell/kowainik/validation-selective/dist-newstyle/build/x86_64-linux/ghc-8.8.3/validation-selective-0.0.0.1/build
-odir
/home/shersh/haskell/kowainik/validation-selective/dist-newstyle/build/x86_64-linux/ghc-8.8.3/validation-selective-0.0.0.1/build
-hidir
/home/shersh/haskell/kowainik/validation-selective/dist-newstyle/build/x86_64-linux/ghc-8.8.3/validation-selective-0.0.0.1/build
-stubdir
/home/shersh/haskell/kowainik/validation-selective/dist-newstyle/build/x86_64-linux/ghc-8.8.3/validation-selective-0.0.0.1/build
-i
-i/home/shersh/haskell/kowainik/validation-selective/dist-newstyle/build/x86_64-linux/ghc-8.8.3/validation-selective-0.0.0.1/build
-isrc
-i/home/shersh/haskell/kowainik/validation-selective/dist-newstyle/build/x86_64-linux/ghc-8.8.3/validation-selective-0.0.0.1/build/autogen
-i/home/shersh/haskell/kowainik/validation-selective/dist-newstyle/build/x86_64-linux/ghc-8.8.3/validation-selective-0.0.0.1/build/global-autogen
-I/home/shersh/haskell/kowainik/validation-selective/dist-newstyle/build/x86_64-linux/ghc-8.8.3/validation-selective-0.0.0.1/build/autogen
-I/home/shersh/haskell/kowainik/validation-selective/dist-newstyle/build/x86_64-linux/ghc-8.8.3/validation-selective-0.0.0.1/build/global-autogen
-I/home/shersh/haskell/kowainik/validation-selective/dist-newstyle/build/x86_64-linux/ghc-8.8.3/validation-selective-0.0.0.1/build
-optP-include
-optP/home/shersh/haskell/kowainik/validation-selective/dist-newstyle/build/x86_64-linux/ghc-8.8.3/validation-selective-0.0.0.1/build/autogen/cabal_macros.h
-this-unit-id
validation-selective-0.0.0.1-inplace
-hide-all-packages
-Wmissing-home-modules
-no-user-package-db
-package-db
/home/shersh/.cabal/store/ghc-8.8.3/package.db
-package-db
/home/shersh/haskell/kowainik/validation-selective/dist-newstyle/packagedb/ghc-8.8.3
-package-db
/home/shersh/haskell/kowainik/validation-selective/dist-newstyle/build/x86_64-linux/ghc-8.8.3/validation-selective-0.0.0.1/package.conf.inplace
-package-id
base-4.13.0.0
-package-id
deepseq-1.4.4.0
-package-id
selective-0.4.1-32e5c7136591ba0bf8a6d8dbf5980fd82353e0434978fd1a3fc79efd9ad7b288
-XHaskell2010
-XConstraintKinds
-XDeriveGeneric
-XDerivingStrategies
-XGeneralizedNewtypeDeriving
-XInstanceSigs
-XKindSignatures
-XLambdaCase
-XOverloadedStrings
-XRecordWildCards
-XScopedTypeVariables
-XStandaloneDeriving
-XTupleSections
-XTypeApplications
-XViewPatterns
Validation
-Wall
-Wcompat
-Widentities
-Wincomplete-uni-patterns
-Wincomplete-record-updates
-Wredundant-constraints
-fhide-source-paths
-Wmissing-export-lists
-Wpartial-fields
-Wmissing-deriving-strategies
-hide-all-packages
```

Content of the `out` file specifies only flags found in the `.cabal` file, not in the specified module (e.g. the `src/Validation.hs` module has the `-XDataKinds` language pragma enabled). How should I patch the `hie.yaml` file or the call to `hie-bios` to make it work for my case?

### Environment

OS: Ubuntu 18.04
Cabal version: `3.0.0.0`
GHC version: `8.8.3`
hie-bios version: `hie-bios version 0.4.0 compiled by GHC 8.8.3`

**Comment by mpickering** [comment]
This seems like it works by accident? The point of the `flags` command is for debugging, I don't think it was *intended* to work with the `HIE_BIOS_OUPUT` envvar.

Also I am imagining that you want to know that `-XDataKinds` is enabled by a language pragma, hie-bios will never tell you that because the language pragma is parsed directly into the DynFlags rather than via a command line option. 

So overall it sounds like things won't work out exactly as you hoped. The way to load a specific file is to create a GHC session with the flags reported by hie-bios and then load the file using one of the other helper functions provided by the library. Perhaps your exact use case can help guide us to a solution.

**Comment by chshersh** [comment]
@mpickering Thanks for the detailed explanation of the existing behaviour. Yes, ideally I'd like to get a list of language pragmas and GHC options used for a single module. I imagine an API like below:

```haskell
getModulesFlags :: HieBiosConfig -> [ModuleName] -> IO (Map ModuleName [Flags])
```

where `[Flags]` for the specific module is `cabalFileFlags <> thisModuleFlags`. I'm okay with writing this function by myself, and I would be really grateful if you could point to some relevant functions, specifically relevant `hie-bios` functions, how to start a GHC session and how to extract flags after the module is loaded.

**Comment by chshersh** [comment]
I was interested mostly in `{-# LANGUAGE #-}` extensions used in a file, combined together with `default-extensions` from the Cabal file. Now, there exist the `extensions` library and a tool, that allows me to do this:

* https://github.com/kowainik/extensions
