### ISSUE TITLE
Config for a component with multiple directories in hs-source-dirs?

### ISSUE THREAD

**Issue by Avi-D-coder** [mpickering/hie-bios#176]
`hs-source-dirs` can take multiple directories how should I express that in an hie.yaml file?

**Comment by jneira** [comment]
@fendor could correct me, but i think you have to repeat one entry in the multi cradle for each source dir, repeating the component

**Comment by fendor** [comment]
Yeah, that should work.

**Comment by jneira** [comment]
I think the issue can be closed
