### ISSUE TITLE
Make package db filepath absolute

### ISSUE THREAD

**Issue by fendor** [mpickering/hie-bios#192]
Single modification to https://github.com/mpickering/hie-bios/blob/master/src/HIE/Bios/Environment.hs#L173 required

**Comment by jneira** [comment]
Sorry, i missed the rationale of this change, could you add some context, please?

**Comment by fendor** [comment]
To make it easier to use these flags irrespective of the location.
My personal use-case was that I used `hie-bios flags compiler/../` to produce flags usable for a direct cradle to have my changes to ghc available in ghcide using the bootstrap compiler 8.8.3.
While I had to remove some unnecessary import paths, I also had to make any flags absolute that werent already, in this case the `--package-db=` was relative to my ghc source directory.
