### ISSUE TITLE
Specify flags for cabal cradle

### ISSUE THREAD

**Issue by lf-** [mpickering/hie-bios#240]
I want to be able to specify cabal flags in my `hie.yaml` to enable my example executable which is `buildable: False` by default, conditional on the `example` flag not being present.

**Comment by fendor** [comment]
Can't you achieve that by creating a `cabal.project.local` file?

**Comment by lf-** [comment]
@fendor probably, but I had no idea to try that first. I'll have a crack at it. Thanks!

**Comment by lf-** [comment]
Yep, that seems to work. I'd appreciate if it were mentioned in the README as being the way to do this :)

Assuming it's not already and I didn't just miss it.
