### ISSUE TITLE
Incorrect version bound for `yaml` dependency

### ISSUE THREAD

**Issue by runeksvendsen** [mpickering/hie-bios#246]
The module `HIE.Bios.Config` imports [`Data.Yaml.Internal (Warning(..))`](https://github.com/mpickering/hie-bios/blob/0ed760498db85d0e18c72260f9866ef5cbac35bb/src/HIE/Bios/Config.hs#L33). The `yaml` package does not export this until version `0.10.0`, but [`hie-bios.cabal`](https://github.com/mpickering/hie-bios/blob/0ed760498db85d0e18c72260f9866ef5cbac35bb/hie-bios.cabal#L208) requires only at least `0.8.32`.

**Comment by fendor** [comment]
Welp, this is going to be another major version bump :(

**Comment by ndmitchell** [comment]
A metadata revision should be enough.
