### ISSUE TITLE
Mixins support

### ISSUE THREAD

**Issue by Martoon-00** [mpickering/hie-bios#260]
In one of the projects, we are trying to use mixins feature to hide the default Prelude module and provide our own. Then I'm trying to build it with `ghcide`, but my build fails, saying

```
Ambiguous module name ‘Prelude’:
  it was found in multiple packages:
  base-4.13.0.0 morley-prelude-0.3.0
```

I reported this issue (https://github.com/haskell/ghcide/issues/890), however it looks like the problem comes from `hie-bios`.

For instance, when I try it on our [Morley repository](https://gitlab.com/morley-framework/morley/), commit `e9a00b61bb`:

* `hie-bios check code/morley/src/Util/Text.hs` reports the same error as above.
* `hie-bios debug code/morley/src/Util/Text.hs` mentions ` -package-id=base-4.13.0.0`, but the information about hidden `Prelude` is not present.

I'm using `stack`, and `hie.yaml` provided by `gen-hie`. 

So my guess is that mixins are not yet supported, is that true? If so, are there plans on implementing this feature?

**Comment by fendor** [comment]
Does `cabal repl` or `stack repl` work for your project? We rely on that and if that works, `hie-bios` should work, too, imo.

**Comment by Martoon-00** [comment]
Actually no, `stack repl` also does not work in my case. Can't make `cabal` work for some other reasons, but I think it shouldn't have any problems with mixins.

Then I suppose I have to wait for https://github.com/commercialhaskell/stack/issues/5077 to be resolved first, will try to reopen this issue then. Thanks for your quick reply!
