### ISSUE TITLE
Using NIX_GHC_LIBDIR is surprising and undocumented

### ISSUE THREAD

**Issue by mpickering** [mpickering/hie-bios#273]
It is surprising (and undocumented) to check for `NIX_GHC_LIBDIR` in order to work out which libdir to use.

My situation was that I explicitly set the compiler for a bios cradle but NIX_GHC_LIBDIR was still being incorrectly consulted to pick the libdir of a different compiler.

The workaround was to call `unset NIX_GHC_LIBDIR` in the bios script.

**Comment by bgamari** [comment]
Indeed issue had me quite confused for quite a while. In particular, I was working on GHC in a `ghc.nix` `nix-shell` (which provides `ghc-8.10.2` by default) but had overridden the bootstrap compiler using `./configure GHC=ghc-8.10.4`. Perplexingly, I then observed that HLS was *still* trying to use GHC 8.10.2. Trying again outside of `nix-shell` avoids this issue, as does unsetting `NIX_GHC_LIBDIR`.

It's quite unclear to me why it would be beneficial to refer to `NIX_GHC_LIBDIR`. The reasoning is ostensibly to support users in `nix-shell`. However, presumably in `nix-shell`the  `ghc` executable should also be in `PATH`. Consequently, it seems to me that referring to `NIX_GHC_LIBDIR` is redundant and only introduces the potential for confusion.

**Comment by bgamari** [comment]
Doing a bit more investigation, I suspect this behavior was introduced in https://github.com/haskell/haskell-language-server/commit/8b2e804fc701955907354aa9f0994990a27afc75.

**Comment by bgamari** [comment]
It seems that issue references in the Git history were rewritten to `haskell/ghcide` during the `ghcide` migration. The original MR was https://github.com/digital-asset/daml/pull/1670.

**Comment by bgamari** [comment]
@nc6, do you recall why digital-asset/daml#1670 was necessary?  Shouldn't the `ghc` executable should always be in `PATH` in the `nix-shell` environment of a Haskell derivation?

**Comment by nc6** [comment]
I can't recall specifically - I remember submitting the patch during Zurihac, and it fixed the demo build for ghcide at the time. Maybe something to do with https://github.com/haskell/ghcide/blob/3ae24dfbb347c69160fd724d319d9dba107acf8f/docs/Setup.md#issues-with-nix?
