### ISSUE TITLE
stack --nix

### ISSUE THREAD

**Issue by jamesdbrock** [mpickering/hie-bios#297]
I'm trying to make a `hie.yaml` cradle for a Stack-based project with Nix integration. https://docs.haskellstack.org/en/stable/nix_integration/

The `stack.yaml` has Nix integration turned off by default

```yaml
nix:
    enable: false
```

but I want to enable Nix integration for haskell-language-server. If I could tell haskell-language-server to invoke Stack as `stack --nix` then that would enable Nix integration.

Is there a way to configure the `hie.yaml` so that it invokes Stack as `stack --nix`?

**Comment by jamesdbrock** [comment]
I guess the `stackYaml` option is one possibility.

**Comment by jamesdbrock** [comment]
Because we don't want to have to assume that all users of this project have Nix installed, @fendor .

Except in the special case of haskell-language-server, I want to assume users have Nix installed, because I don't see any other way to provide a zero-setup configuration for haskell-language-server.

**Comment by jamesdbrock** [comment]
Maybe the answer is “no, there is no way to configure the `hie.yaml` so that it invokes Stack as `stack --nix`.” Which is fine.

**Comment by jamesdbrock** [comment]
Or maybe this question is for the haskell-language-server project?

**Comment by fendor** [comment]
Here is the right place and currently, there is no way to configure `hie.yaml` to invoke `stack --nix`.
