### ISSUE TITLE
Report what files are dependencies of the Cradle

### ISSUE THREAD

**Issue by ndmitchell** [mpickering/hie-bios#35]
See https://github.com/digital-asset/ghcide/issues/50, which wants ghcide to reload when you update your .cabal file. One option is that a `Cradle` should have an extra field `cradeDependencies :: [FilePath]` which would give the files which the cradle uses.

**Comment by fendor** [comment]
So, cradleDependencies are files that ghcide needs to watch for changes for, right?
E.g. for cabal that would be a `cabal.project` and `*.cabal` file and for stack `stack.yaml`, `package.yaml` and `*.cabal`?

**Comment by ndmitchell** [comment]
@fendor - yep!

**Comment by fendor** [comment]
One more questions, should it only contain files that exist, or all files that may be interesting? E.g. cabal.project may not always exist but as soon as one is added, we would want to know about it right?

**Comment by ndmitchell** [comment]
The files don't have to exist - anything relevant would be useful.

**Comment by fendor** [comment]
After talking with @mpickering, dependencies of a cradle should be loaded when loading a cradle and it should be possible to query the corresponding build tool.
Therefore, I propose the following API changes:

```haskell
-- | The environment where this library is used.
data Cradle = Cradle {
  -- | The project root directory.
    cradleRootDir    :: FilePath
  -- | The action which needs to be executed to get the correct
  -- command line arguments
  , cradleOptsProg   :: CradleAction
  } deriving (Show)

data CradleAction = CradleAction 
    { actionName :: String
    , getDependencies :: IO [FilePath] 
    -- ^ Files that cause the cradle to change, may be monitored to reload a cradle
    , getOptions ::  (FilePath -> IO (ExitCode, String, [String]))
    -- ^ Options to compile a file in the cradle with.
    }
```

Further, extend the Cradle config to include a field cradle deps. This allows users to work around any missed cradle dependencies by supplying them themselves in `hie.yaml`:
```haskell
data CradleType 
   = Cabal { component :: Maybe String }
   | Stack
   | Bazel
   | Obelisk
   | Bios { prog :: FilePath, deps :: Maybe FilePath }
   | Direct { arguments :: [String] }
   | Default
   deriving (Show)

data CradleConfig = CradleConfig
   { cradleType :: CradleType
   , cradleDependencies :: Maybe [FilePath]
    -- ^ Bikeshed, `Maybe` is not necessary, empty list might be good enough 
   }
```

Note, the changes to `Bios` CradleType, which now also includes the path to a program that produces cradle dependencies.

**Comment by ndmitchell** [comment]
Looks sensible to me!

**Comment by mpickering** [comment]
Sounds right to me. 

* Make sure you properly combine together the dependencies directly specified by the user and dependencies reported by the bios program.
* Just use `[FilePath]` rather than `Maybe [FilePath]`.
* Document the new addition (are filepaths expected to absolute? relative?)
