### ISSUE TITLE
NoImplicitPrelude breaks a package

### ISSUE THREAD

**Issue by domenkozar** [mpickering/hie-bios#37]
I'm using stack.

Package A uses `NoImplicitPrelude` default extension but depends on package B which doesn't. Package B fails to compile because ghcide assumes `NoImplicitPrelude`.

PS: I'm not entirely sure if this is an issue here or in ghcide

**Comment by domenkozar** [comment]
Seems like it's an upstream issue: https://github.com/commercialhaskell/stack/issues/2173

**Comment by mpickering** [comment]
Yes, it's a bug in stack trying to be clever creating a single component when there are two. I'll comment further on the GHC issue you opened.
