### ISSUE TITLE
GHC arguments with spaces are broken up (wrappers/cabal)

### ISSUE THREAD

**Issue by roberth** [mpickering/hie-bios#38]
For example the cabal file may have

```
   ghc-options: "-with-rtsopts=-maxN8 -qg"
```

which will become

```
"-with-rtsopts=-maxN8","-qg"
```

This is where the space is lost: https://github.com/mpickering/hie-bios/blob/3e4e76064ade245bbe47520bd3eeb7cecdde1070/wrappers/cabal#L4

**Comment by mpickering** [comment]
Do you know how to fix this? Write the flags to a temp file perhaps?

**Comment by roberth** [comment]
echo "${*@Q}"

Is one way to do it, but you'll have to parse the arguments like bash would.
Perhaps simpler is to separate by NUL bytes, which should be lossless even without escaping.

    for a in "$@"; do printf "%s\0" "$a"; done

Seems to work:

    $ foo a b "p q" | cat -v
    a^@b^@p q^@

**Comment by domenkozar** [comment]
Seems to be fixed in https://github.com/mpickering/hie-bios/commit/25473863c0af67ec9d91651e4548aef7a2fedabe

**Comment by mpickering** [comment]
Indeed, should be fixed now. I will do a release today.
