### ISSUE TITLE
Adding a "None" cradle

### ISSUE THREAD

**Issue by mpickering** [mpickering/hie-bios#52]
There are sometimes Haskell files in projects you just don't want to attempt to load into an IDE as you know they will fail. Therefore I want to add a "none" cradle type which communicates to an IDE that it should just ignore these files and not try to load them into a session.

Some examples:

1. The hundreds of test files in GHC's code base
2. The hundreds of test files in haskell-src-exts code base

However, this complicates the API a little bit.

The main change is `cradleOptsProg :: CradleAction` is modified to return `CradleLoadResult CompilerOptions`. Therefore the client is responsible for handling any errors which might occur. 

See https://github.com/mpickering/hie-bios/pull/51 for the implementation.

Does this change make sense for ghcide @ndmitchell ?

**Comment by ndmitchell** [comment]
Makes sense! Will take some integration, but just work, a good idea in principle.
