### ISSUE TITLE
Windows cradles start up slower

### ISSUE THREAD

**Issue by ndmitchell** [mpickering/hie-bios#55]
Windows Stack/Cabal cradles first compile a binary. It would be much nicer if they didn't have to every time. Perhaps put it in a known location in temp, e.g. hie-bios-windows-helper-v1.exe, and if it already exists avoid recompiling it each time?

**Comment by jneira** [comment]
I can try to implement this, if nobody is already working on it.

**Comment by mpickering** [comment]
If it's cached then the location should be in `$XDG_CACHE_HOME/hie-bios/...`
