### ISSUE TITLE
Add optional list of components to stack cradle options

### ISSUE THREAD

**Issue by mitchellwrosen** [mpickering/hie-bios#65]
This would allow you to use the `stack` cradle in a context where you may not want to load every package defined in your `stack.yaml` at once (e.g. in a big monorepo).

**Comment by mpickering** [comment]
I think this is an issue with how `ghcide` uses the stack cradle. AFAIU, it just passes an empty path to the cradle which means that stack loads everything.

**Comment by ndmitchell** [comment]
Currently, yes, ghcide does that. It's something that needs fixing at some point.

**Comment by afcowie** [comment]
I'm not sure if this is the same issue, but I'm not sure how to get `cradle: {stack}` to load test dependencies? Running in a checkout of **ghcide** I get errors like

```
File:     ./test/exe/Main.hs
Range:    26:7-26:23
Source:   not found
Severity: DsError
Message: 
  Could not find module ‘Test.Tasty.HUnit’
  It is not a module in the current program, or in any known package.
...
Files that failed:
 * ./test/exe/Main.hs
 * ./test/src/Development/IDE/Test.hs

Completed (39 files worked, 2 files failed)

```

@ndmitchell I'm pretty sure you showed dogfooding the _ghcide_ program in your own code, so I'm missing something obvious, I assume.

**Comment by jneira** [comment]
I've hit the same issue than @afcowie using directly `hie-bios` (master):

```
D:\ws\haskell\hie-bios>hie-bios check tests\ParserTests.hs
cradle
  Cradle {cradleRootDir = "D:\\ws\\haskell\\hie-bios", cradleOptsProg = CradleAction: stack}
hie-bios: <command line>: cannot satisfy -package tasty-1.2.3
    (use -v for more information)
```

But clearly it is a separate issue: `hie-bios` should be able to load all stack components before optionally only load some of them!

**Comment by mpickering** [comment]
@afcowie I don't know how to reproduce your issue but I would like to if you can tell me how. 

@jneira I reproduce your issue. The problem is that `stack repl tests/ParserTests.hs` fails. If you can debug that then the stack cradle would work but it's a mystery to me why it fails.

**Comment by afcowie** [comment]
@mpickering ok, let's see. As far as I can tell it's any project with e.g. a `library` _and_ a `test-suite` where the tests binaries depend on things (like say **hspec** or **hedgehog**) that the core `library` does not.

Do you want an example project you can clone/unpack and try for yourself?

**Comment by mpickering** [comment]
You can now explicitly specify a component.

**Comment by ZzAntares** [comment]
Hi @mpickering, sorry to ask here but it seems relevant, will this:

```
cradle:
  stack:
    component: "myproject:test:myproject-tests"
```

also load the `lib` component? Or should be ...

```
cradle:
  stack:
    component:
      - "myproject:test:myproject-tests"
      - "myproject:lib"
```

?

**Comment by fendor** [comment]
This should be a multi cradle, e.g.
````yaml
cradle:
  stack:
    - path : "./src"
      component: "myproject:lib"
    - path : "./test"
      component: "myproject:test:myproject-tests"
```
